version: "3.9"
services:
  db:
    image: postgres:16
    container_name: psis_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: tpfinal
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: a.123456
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: